Cargo.toml
src/lib.rs
src/transport.rs
tests/timeouts.rs

Read pending error messages from libcurl for our multi handle _before_ detaching the easy handle, otherwise libcurl will discard the errors before we can read them. This was causing the request to spin forever in the case of a timeout, since libcurl finished handling the request, but we missed the notification of the status change.
Also add some helpful trace logging to debug these kinds of issues.

Issue #3: Fix timeouts not being respected

---

src/internal/request.rs
src/options.rs

Provide request options for configuring a custom client certificate and private key for SSL/TLS connections.
Also expose the option for listing specific SSL/TLS cipher names to enable.
Resolves #19.

Add more configurable SSL options

---

src/internal/notify.rs

Looks like some refactoring wasn't finished in the windows `#cfg` sections. Might be worth adding an Appveyor based test in future, to ensure Windows configurations compile? 🙂
Closes #23.

Fix Windows configuration issues in notify

---

.github/main.workflow
.gitignore
Cargo.toml
examples/simple.rs
src/internal/agent.rs
src/internal/request.rs

Previously, certain critical lines of code were accidentally wrapped in `debug_assert!` when `assert!` would have been appropriate. It seems that I misunderstood the implications of `debug_assert!`; the end result was that a critical piece of code, the code that resolves the request future, was put inside one such statement, resulting in it never being run in release mode.
This issue manifested itself in the internal future for a request never getting resolved before being closed, resulting in the caller getting a `Canceled` error.
- Add some code to ensure that dropping a `Client` is managed correctly.
- Run an example compiled in release mode during builds to ensure problems like these are caught before being merged.
Fixes #30.

 fix: Ensure important code runs in release mode

---

Cargo.toml

Upgrades the bundled version of libcurl to 7.65.1.

Bump curl-sys to 0.4.20 to fix #34

---

Cargo.toml
src/agent.rs
src/body.rs
src/client.rs
src/handler.rs
src/parse.rs

- **Remove auto_enums and static_assertions**: In response to issue #41, these two are dependencies that are hardly required and barely used, and both are heavy in the macro department and add lots of compile time.
- **Remove regex**: Regex is another big offender, which takes up a lot of binary space and also has a somewhat long compile time as well. Since we use it only to parse header lines, rewrite those parsers without regex and then remove the dependency.
This PR takes the total number of dependencies (without any features) from 61 to 46. According to `cargo bloat`, the biggest remaining dependency is the http crate (oddly enough), and removing that is not an option.

Dependency tree trimming

---

examples/parallel_requests.rs
examples/simple.rs
src/client.rs
src/lib.rs
src/wakers.rs

- Rename `Client` to `HttpClient` and `ClientBuilder` to `HttpClientBuilder`. For usability it helps to include the client type in our prelude, but the name `Client` is just a little too generic to do that. Using the name `HttpClient` is much less ambiguous as to what kind of client is in question. It's also a very common type name for HTTP clients and adds to familiarity.
- Improve the documentation for `HttpClient` methods with some examples as well.

Rename Client to HttpClient and improve client docs

---

Cargo.toml
src/agent.rs
src/body.rs
src/client.rs
src/handler.rs
src/io.rs
src/response.rs
src/wakers.rs

Change the main synchronous APIs to use a different mechanism other than `block_on` to wait for completion by using a crossbeam channel instead of a futures oneshot channel.
This has a couple of advantages:
- We no longer need `futures_channel`, so we can remove it from our dependency tree.
- It is possible that blocking on a crossbeam's native `recv()` is more efficient than running a local executor to poll a response future.
Also trim down the futures crate to the pieces we actually use.

Implement synchronous API without block_on

---

src/client.rs
src/handler.rs
tests/request_body.rs

When sending a POST request with a body, the body length must be specified using CURLOPT_POSTFIELDSIZE, not CURLOPT_INFILESIZE like for other request methods.
If the user provides a `Content-Length` header, use that as the request body size, even if the body itself has an unknown size.
In addition, for bodies with an unknown size, set `Transfer-Encoding: chunked` explicitly to ensure that curl knows to use chunked encoding.
Add more comprehensive tests for sending a request body to ensure that such bugs are caught in the future.
Fixes #51.

fix: use CURLOPT_POSTFIELDSIZE for POST body

---

Cargo.toml
src/agent.rs
src/client.rs
src/handler.rs
tests/response_body.rs

Dropping an `HttpClient` will no longer necessarily shut down the curl agent, which previously caused the response body of any active transfers to simply return EOF without explanation.
This PR fixes this issue with two changes:
- Reading from the response body will now return `io::ErrorKind::ConnectionAborted` when EOF is reached due to abnormal termination of the corresponding request handler. This will ensure that a visible error is returned in case the agent thread errors or panics abnormally.
- Response bodies returned by `HttpClient` include a shared reference to the agent handle, ensuring that the agent is kept alive until both `HttpClient` _and_ all associated response streams are dropped.
Fixes #64.

Change HttpClient drop behavior

---

benchmarks/benches/download.rs
benchmarks/src/lib.rs
examples/simple.rs
src/client.rs
src/config.rs
src/cookies/psl/mod.rs
src/handler.rs
src/lib.rs
src/request.rs
tests/encoding.rs
tests/headers.rs

Reqwest has a config option to disregard SSL validation. This PR enables that functionality in isahc. It is a feature I need for my own crate, where I just need to verify that the links are accessible, even if unsafe. Sometimes, libcurl will report as unsafe while a browser will say it's fine, for example https://www.iep.utm.edu/desert/
I also ran `cargo fmt`, resulting in some amount of reformatting elsewhere.

Add the ability to ignore SSL validation

---

src/client.rs
src/config.rs
src/request.rs
tests/redirects.rs

Fix auto referer option not being respected on outgoing headers. Add a test to make sure it is working.
Also refactor how configuration options are applied to curl easy handles to make the code a little more manageable and easier to understand.

Fix auto referer not setting referer header

---

src/handler.rs

I was playing around with surf and was wondering why I could only get one of multiple `set-cookie` headers... turns out `HeaderMap::insert` overrides any existing value(s) for the given key.

Keep all instances of the same response header

---

src/agent.rs
src/client.rs
src/config.rs
src/request.rs

There are good use cases why you might want to limit the size of the connection cache, or disable it altogether.
Add `connection_cache_size` to `HttpClientBuilder`, which allows you to override the defaults and set a maximum number of persistent connections to keep in the cache, or to disable connection caching altogether.
Fixes part of #79.

Add options for configuring the connection cache

---

examples/badssl.rs
src/auth.rs
src/client.rs
src/config/mod.rs
src/config/ssl.rs
src/request.rs

Replace `danger_allow_unsafe_ssl()` and `ssl_no_revoke()` with `ssl_options()`, which accepts multiple `SslOption` flags as an argument. Each flag does one specific thing, allowing users to more precisely control which insecurities they wish to indulge in. 😉
This API also gives us more breathing room for implementing more flags in the future without polluting builders with method upon method of this stuff.
Also moved SSL-related config definitions into an internal `ssl` module to prevent the main config module from becoming too unwieldly.
Fixes #83.
This is a breaking change.

Separate various SSL options into individual flags

---

examples/http2.rs
src/client.rs
src/config/mod.rs
src/request.rs
tests/version.rs

Replace `preferred_http_version()` with a new `VersionNegotiation` API that provides more explicit and clear settings for how HTTP versions will be negotiated. This also provides support for "HTTP/2 Prior Knowledge", and will allow us to support HTTP/3 when it comes in the future in a backwards-compatible way.
This is implemented almost exactly as proposed in #108.
Fixes #108.

Add new VersionNegotiation API

---

Cargo.toml

once https://github.com/sagebind/sluice/pull/7 is merged isahc will no longer depend on the `syn` crate, which should improve compile times and drops the dependency count from 41 to 34

use 'default-feature = false' on futures-util

---

src/body.rs
src/client.rs
tests/request_body.rs
tests/response_body.rs

- Prefix constructor-like functions with `from_` for consistency.
- Remove text-related methods (fixes #142).
- Remove `Bytes` from public API for more stability.

Breaking API changes to Body

---

src/response.rs
src/text.rs

Update the return value of `ResponseExt::text_async` to conditionally implement `Send` when the type of body also implements `Send`, which is true of `Body`.
This _isn't_ a breaking change because the return type of `text_async` is unnameable, and does not implement _less_ traits than before.
Fixes #173.

Implement Send for text_async when body implements Send

---

src/client.rs
src/config/mod.rs
src/error.rs
tests/headers.rs

Hi @sagebind, 
Tried to come up with something for the issue #180 .
Had to change the `default_header` signature from a `self` to `mut self`.
( In case I am going in completely wrong direction, please let me know. )

WIP: fix #184

---

.github/workflows/ci.yml
.gitignore

`-Zno-landing-pads` was removed from nightly recently (https://github.com/rust-lang/rust/pull/70175), which seems to mess up grcov reports (https://github.com/mozilla/grcov/issues/427). Even after figuring out how to set `panic=abort` on all the correct profiles, it seems that it still reports odd numbers relative to when `-Zno-landing-pads` worked.
Switch to [tarpaulin](https://github.com/xd009642/tarpaulin) for now which has also caught my eye recently.

Fix code coverage runs

---

src/client.rs
src/error.rs

Thinking about future compatibility, we might want to leverage interceptors someday as an implementation detail for how default headers are set. To avoid locking us in the current implementation, do not expose the default `HeaderMap` as a direct reference. Instead, for users who want to set headers in bulk, provide `default_headers` which takes an iterator of key-value pairs and replaces all existing headers. That allows users to do the same kind of things without relying on a mutable `HeaderMap` being exposed.
Also tweak some docs.

Replace default_headers_mut with default_headers

---

Cargo.toml
src/agent.rs
src/client.rs
src/config/dns.rs
src/config/mod.rs
src/cookies/mod.rs
src/cookies/psl/mod.rs
src/handler.rs
src/lib.rs
src/task.rs
src/text.rs

Emit all logs as `tracing` events, with backward compatability with log records.
Fixes #77.

Migrate from log to tracing

---

examples/logging.rs
examples/tracing.rs
src/agent.rs
src/client.rs
src/handler.rs

This cripples the tracing subscriber ability somewhat, but tones down the noisy logs coming from the `tracing::span` target.
A better solution would be for enter/exit logs from `tracing::span` to be emitted always at the `Trace` level in the `tracing` library.
Fixes #192.

Change all tracing spans to Trace level

---

.github/workflows/ci.yml

- Jump back to the latest tarpaulin version which fixed doctests https://github.com/xd009642/tarpaulin/issues/402.
- Don't fail CI if codecov fails to upload because of https://github.com/codecov/codecov-action/issues/81

Update analysis CI job

---

src/config/mod.rs
tests/headers.rs

Fix a bug where empty or blank header values were not being sent because we were using the wrong libcurl string syntax for these special headers.
Fixes #209.

Fix empty and blank request headers not being sent

---

src/client.rs

Based on feedback from Stenberg himself in https://github.com/curl/curl/issues/5717, it doesn't really make much sense to set both `nobody` _and_ `upload` on the same request in order to fulfill weird HEAD requests with a request body. Change (and simplify) to use `nobody` for normal HEAD requests, and `upload` + `customrequest` otherwise.

Don't combine nobody with upload

---

src/handler.rs
src/response.rs
tests/net.rs

Add `ResponseExt::local_addr` and `ResponseExt::remote_addr` methods which allow you to get the local and peer socket addresses used for the request, respectively.
Related to #220.

Add local_addr and remote_addr

---

Cargo.toml

I have some builds that I'd like to have produce a fully static binary, and for that I need to expose `curl/static-ssl`. I think for the general case having it dynamically linked is fine (I mean no one has complained thus far!), so I've left it out of the default features for now, but would be happy to add it there if you feel it's worth it.
Thanks!

add static-ssl feature to mirror curl/static-ssl

---

src/client.rs
src/config/mod.rs
tests/encoding.rs

Add a new option to disable (or enable) automatic response decompression. This also influences the default value of the `Accept-Encoding` header, but this can be overrided.
See #227.

Add option to disable automatic decompression

---

README.md

It's always nice when projects are open and honest about their shortcomings as well as their strengths. Add a section to the readme that highlights some key weaknesses of Isahc, along with some recommended alternatives.

Add a "Why not use" section to readme

---

src/client.rs
src/config/mod.rs

This patch uses the newly exposed curl configuration allowing for a client to set up a connection cache TTL.
Closes #93

Add Connection Cache TTL

---

src/error.rs
src/handler.rs
tests/timeouts.rs
testserver/src/lib.rs
testserver/src/mock.rs
testserver/src/response.rs

If a request errors after the response headers have already been received, but the full response body has not been read yet, then the response body stream will begin returning EOF without any other explanation other than what is written to the logger. This gives the appearance that everything is fine but half of the response body is missing.
To fix this, be sure to communicate to the response stream when a transfer error occurs while streaming the response body, so that the next call to read from the response will return an appropriate error instead of an unexplained EOF.
This is especially an obvious problem when combined with the timeout option, which can very likely occur during reading of the response body, whereas most other errors are likely to occur before that time.
First raised …

Fix timeouts causing unexplained EOFs

---

src/config/mod.rs
tests/timeouts.rs

How timeouts are applied was a bit vague in our documentation and was causing some confusion. Add more detail to make it hopefully more clear as to what the timeout does, in particular that the timeout is still active even once the response headers are received and while the body has not been yet read.

Improve documentation on timeouts

---

.github/workflows/ci.yml
src/client.rs
tests/redirects.rs

Fix a regression from #240 that caused redirect policies to be ignored if being set client-wide instead of per-request.
Fixes #250.

Fix client-wide redirect policy not respected

---

Cargo.toml
src/agent.rs
src/body.rs
src/client.rs
src/handler.rs
src/interceptor/mod.rs
src/response.rs
src/task.rs
src/text.rs

Tis the season to be trimming the tree! Reducing dependencies where it makes sense is a regular task for Isahc to ensure shorter compile times, binary size, or package size.
This time around the goal was to eliminate `futures-util` from the essential dependencies, since it has long compile times. This included swapping out for `futures-lite` where needed, or just using our own code, as well as updating Sluice to remove `futures-util` from there as well.
Also a goal was to unify our preferred channel implementation, since we currently use _both_ `futures-channel` and `crossbeam-channel`, depending on the scenario. Here we can replace both with `flume` which has the nice property of supporting both sync and async operations on one channel.

Trim some heavy dependencies

---

src/client.rs
src/config/mod.rs
src/request.rs

Support specifying the ip protocol version to use, like to `curl -4` and `curl -6`.
fixes #252

Add support for forcing a specific ip protocal version

---

Cargo.toml
src/handler.rs
src/redirect.rs
src/response.rs
tests/redirects.rs

Previously we were relying on curl to resolve the redirect location with `CURLINFO_REDIRECT_URL`, but this value is only populated once the response body stream has been consumed and the handle is complete. This means that redirects were working properly if the response containing the redirect had an empty body, but not if a nonempty body is included.
Since we don't really want to wait for the response body to be consumed before we decide whether we should redirect or not, change the redirect interceptor to derive the redirect location ourselves. Since the algorithm is nontrivial, pull in the `url` crate to do this resolution.
Also add a test for following redirects when response bodies are present to catch this bug.
Fixes #250.

Fix redirect handling with response bodies

---

.github/workflows/ci.yml
Cargo.toml
README.md
src/client.rs
src/config/dial.rs
src/cookies/cookie.rs
tests/redirects.rs
tests/timeouts.rs
tests/utils/mod.rs

1.41 is the version on Debian stable (a common distribution channel) and supports basically everything that we require. Only a few small changes were required to get it to compile with this version.
Fixes #219.

Pin MSRV to 1.41

---

src/agent.rs
src/body.rs
src/client.rs
src/config/mod.rs
src/error.rs
src/handler.rs
src/interceptor/context.rs
src/interceptor/mod.rs
src/interceptor/obj.rs
src/lib.rs
src/macros.rs
src/redirect.rs
src/task.rs
tests/encoding.rs
tests/redirects.rs
tests/timeouts.rs
tests/utils/mod.rs

Update `isahc::Error` to support taking new variants in a backwards-compatible way, as well as hold more error sources when an error is caused by another.
Note that this is the first 1.0 breaking change to land on `master`. If 0.9 needs a patch fix in the future, we'll have to make a 0.9.x branch for it.
Fixes #182.

Error type updates

---

Cargo.toml
src/body.rs
tests/redirects.rs

Remove bytes as a direct dependency, as our small usage does not really justify its inclusion. In addition, update the constructor methods for `Body` to reflect this change. These changes are minor but breaking, but encourage using the `From` traits more so as to reduce copying when possible.

Remove bytes dependency & update Body constructors

---

Cargo.toml
examples/async.rs
examples/stream_cancellation.rs
examples/upload_file.rs
src/agent.rs
src/body/mod.rs
src/body/sync.rs
src/client.rs
src/cookies/interceptor.rs
src/default_headers.rs
src/handler.rs
src/headers.rs
src/interceptor/context.rs
src/interceptor/mod.rs
src/interceptor/obj.rs
src/lib.rs
src/parsing.rs
src/redirect.rs
src/request.rs
src/response.rs
src/text.rs
tests/redirects.rs
tests/request_body.rs

Make the big split between synchronous responses and asynchronous responses, which offers ergonomic improvements and encourages users towards using the right methods by default as discussed in #202. This required the following changes:
- Split `Body` into two distinct types: `AsyncBody` and `Body`, which are asynchronous only and synchronous only, respectively.
- Split `ResponseExt` into three traits: `ResponseExt` for methods that don't use the body, `ReadResponseExt` for synchronous methods that read from the body, and `AsyncReadResponseExt` for async methods that read from the body. This offers some ergonomic improvements as well, as the async response methods can drop the `_async` suffix, and Rust will automatically resolve to the correct method depending on whether the response is …

Split sync and async body into distinct types

---

src/client.rs
tests/encoding.rs

When automatic decompression is enabled and a server returns a `Content-Length` response header for compressed content, `Body::len` was naively returning the unmodified value of `Content-Length` as the body length. This is incorrect because the `Content-Length` in this situation indicates the _compressed_ size of the body, not the uncompressed size.
Since `Body::len` is supposed to be reporting the size of the body that it is returning if known, returning the uncompressed size is confusing and buggy, and can (and does) cause issues for downstream users.
This fixes the issue by simply returning `None` as the body length whenever we are decompressing the response body on the user's behalf, since it is impossible for us to know the uncompressed size ahead of time.
Fixes #265.

Fix body reporting compressed length with auto decompression

---

.github/workflows/commands.yml
rustfmt.toml

Add config for rustfmt as well as a semi-automated workflow for applying it. I'm not a fan of applying it in CI because:
- When used as a condition for CI, a red build is a bit harsh just for formatting issues, when it is trivial to format it without a PR author's involvement.
- Running rustfmt automatically in PRs and pushing if changes were made means that the latest commit doesn't match the PR authors', which less Git-savvy contributors may not know how to deal with. In addition it is just annoying if every other commit is applying another formatting commit.
The idea here is to implement a slash command that can be run manually just prior to merging, if needed.

Add rustfmt config and workflow

---

examples/badssl.rs
examples/client.rs
examples/cookies.rs
examples/http2.rs
examples/parallel_requests.rs
examples/progress.rs
src/client.rs
src/config/mod.rs
src/interceptor/context.rs
src/lib.rs
src/request.rs
tests/auth.rs
tests/cookies.rs
tests/encoding.rs
tests/headers.rs
tests/methods.rs
tests/metrics.rs
tests/proxy.rs
tests/redirects.rs
tests/request_body.rs
tests/timeouts.rs
tests/unix.rs

Remove `Request`, `Response`, and `HttpClient` from the prelude since aren't really ubiquitous enough to deserve that position and glob-importing structs can be more confusing to beginners not sure where a type comes from.
Also clean up some doc examples to show imports to aid in understandability.

Remove structs from prelude module

---

src/handler.rs

Previously we were using two different atomic sources to discover when a response has been dropped, but only emitting a warning for an unconsumed response body if one of the sources indicated a drop. This was causing inconsistent results of when the warning would be emitted. Fix this by having just one source of truth for when the response is dropped.
In addition, change the warning log into an info log instead with a better message. Aborting a response stream is not incorrect and may be intentionally desired by the user. After #257 we could directly suggest using `consume()` in the log message.
See #270.

Fix response body abort warning

---

src/macros.rs
src/response.rs
src/text.rs

Update future types used by `AsyncReadResponseExt` to be `Send` whenever `T` is `Send` as appropriate. Consolidate the newtype futures with a macro that handles conditional `Send` properly to reduce boilerplate and chance of mistakes.
Fixes #283.

Update future types to be Send

---

src/parsing.rs

Previously headers were sent with no whitespace before or after the colon (`:`). This is legal according to RFC 7230, section 3.2, but is somewhat unusual and can cause poorly-written servers to choke on parsing the request. Update the encoder to always add a single space after the colon to be in line with what most parsers should expect.
This has no effect on HTTP/2 or newer, since they use a binary format for headers.
Fixes #286.

Always use a single space after colon for HTTP 1 headers

---

src/cookies/cookie.rs

I hit this bug in my project where the cookie value was `""` - just two quote characters.
On checking the code, I figured that this bug might exist for all quoted cookie values.
The test case I had written for quoted cookie values was failing with this error:
```
failures:
---- cookies::cookie::tests::parse_simple::_r_foo_bar_ stdout ----
thread 'cookies::cookie::tests::parse_simple::_r_foo_bar_' panicked at 'assertion failed: `(left == right)`
left: `"ba"`,
right: `"bar"`', src\cookies\cookie.rs:310:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Previously one extra character was getting stripped from the end.
This commit fixes the index while stripping the end quote.

Fix parsing of quoted cookie values

---

src/macros.rs
src/response.rs
tests/json.rs

Add an async equivalent of `ReadResponseExt::json` for deserializing JSON responses asynchronously.
This allocates and stores the entire response in memory up front, but we have not much choice due to a serde limitation.
Fixes #245.

Add async json response method

---

Cargo.toml
INTERNALS.md
src/auth.rs
src/client.rs
src/config/client.rs
src/config/internal.rs
src/config/mod.rs
src/config/proxy.rs
src/config/redirect.rs
src/config/request.rs
src/parsing.rs
src/redirect.rs
src/request.rs
src/response.rs
tests/net.rs

Refactor how request configuration is represented internally from a purely extension-based model into a centralized struct. This reduces the generalized code somewhat, but makes it easier to understand for people less familiar with the codebase.
More importantly, this delivers a 5-10% performance improvement in synthetic benchmarks, since it greatly reduces the number of wasteful hashmap lookups we do when trying to apply request configuration to an easy handle.

Refactor request configuration internal representation

---

src/config/mod.rs
src/config/request.rs

Expose libcurl's low speed timeout functionality by adding
a `low_speed_timeout()` method to `Configurable`.

Allow setting low speed timeouts via Configurable

---

src/agent/mod.rs
src/agent/selector.rs
src/agent/timer.rs
src/cookies/psl/mod.rs
src/error.rs
src/redirect.rs
tests/redirects.rs

Try to parse the `Location` header as UTF-8 bytes as a fallback if the header value is not valid US-ASCII. This is technically against the URI spec which requires all literal characters in the URI to be US-ASCII (see [RFC 3986, Section 4.1](https://tools.ietf.org/html/rfc3986#section-4.1)).
This is also more or less against the HTTP spec, which historically allowed for ISO-8859-1 text in header values but since was restricted to US-ASCII plus opaque bytes. Never has UTF-8 been encouraged or allowed as-such. See [RFC 7230, Section 3.2.4](https://tools.ietf.org/html/rfc7230#section-3.2.4) for more info.
However, some bad or misconfigured web servers will do this anyway, and most web browsers recover from this by allowing and interpreting UTF-8 characters as themselves even though they …

Handle raw UTF-8 bytes in redirect headers

---

Cargo.toml
src/agent/mod.rs
src/handler.rs

Flume changes its minimum Rust version too often and also recently added a dependency chain involving longer compile times than ideal. Async-channel is comparable to flume for our use-case, is stable, and has a smaller dependency tree.

Replace flume with async-channel

---

.github/workflows/ci.yml
README.md

We need to increase our MSRV to 1.46.0 because this is the [new minimum version required by `socket2`](https://github.com/rust-lang/socket2/tree/8716af6fbf921cf318b6adb3c13259050d96a13a#minimum-supported-rust-version-msrv), which also effectively bumps the minimum version required for the next version of the `curl` crate.

Bump MSRV to 1.46.0

---

Cargo.toml
src/config/ssl.rs

Pull in new bindings for the new blob APIs added to curl in 2020. Bindings were recently added in https://github.com/alexcrichton/curl-rust/pull/384. This of course only works when using a fairly new curl version.
Addresses https://github.com/sagebind/isahc/issues/89.

Add support for in-memory certificates

---

src/client.rs
src/handler.rs

Improve the log message emitted when a connection is closed without being fully consumed. The message now includes a little bit more detail and links to [a new wiki page](https://github.com/sagebind/isahc/wiki/Connection-Reuse) that explains what is going on in more depth.
In addition, the message is no longer emitted for HTTP/2 or HTTP/3 connections (since it is not a problem there), nor if the connection cache is disabled (since _all_ connections are closed anyway).
See #334.

Improve connection reuse log message

---

src/error.rs
src/handler.rs
src/redirect.rs
src/response.rs
tests/net.rs
tests/redirects.rs

Add `local_addr` and `remote_addr` to `Error` which expose the local and remote network addresses of the last used connection for a request before the error occurred, if known.
Fixes #336.

Expose connection info in errors

---

src/client.rs
src/config/mod.rs
src/config/request.rs
tests/expect.rs

Add a configuration option for changing how POST requests behave under HTTP/1.1 and the `Expect: 100-continue` request behavior. Allow the user to change the timeout to a different duration or to disable the header entirely.
Replaces #311.
Fixes #303.

Allow use of Expect header to be configured

---

src/client.rs
tests/response_body.rs

Return true for Body::is_empty for HEAD responses

---

Cargo.toml
src/cookies/cookie.rs
src/cookies/psl/mod.rs

Remove chrono as a dependency to avoid any connection to the transitive [CVE-2020-26235 in `time` 0.2](https://github.com/rustsec/advisory-db/blob/9e93a3df4a54e70f2539a2ecdc3d70beef64c856/crates/time/RUSTSEC-2020-0071.md). This also requires removing chrono from the public API of `CookieBuilder` (added in https://github.com/sagebind/isahc/pull/349), which is probably for the best anyway before it is released so that we aren't tied to it. Expose `SystemTime` types instead, which both chrono and `time` are compatible with, should the consumer of the API choose to use either of those crates.
Replace formatting and parsing of HTTP date formats with the aptly-named    `httpdate` crate, which implements exactly those two operations and no more. As a side benefit this reduces our total …

Replace chrono with httpdate internally

---

src/response.rs

This is already done for bytes, and should speed up async JSON processing
considerably, avoiding needles reallocations.

Preallocate buffer for async json decoding

---

Cargo.toml
README.md
benchmarks/Cargo.toml
examples/simple.rs
src/lib.rs

Add the ability to opt-in to using rustls as the TLS engine for HTTPS requests with a `unstable-rustls-tls` crate feature.
Based on upstream work in https://github.com/alexcrichton/curl-rust/pull/374.
See #199.

Add experimental rustls support

---

build.rs
src/info.rs
src/lib.rs

Add `is_http_version_supported` which allows you to check which HTTP versions are supported by a particular build of Isahc at runtime. This could be used to decide whether an application would choose to enforce HTTP/2 for example, or just to verify that build configuration is as expected.

Allow checking HTTP version support at runtime

---

.github/codecov.yml
.github/workflows/ci.yml
Cargo.toml
src/text.rs
tests/encoding.rs

Add step to CI that compiles and runs all tests against the lowest compatible versions of all crates to ensure that the specified dependency ranges are actually compatible.
See also <https://users.rust-lang.org/t/psa-please-specify-precise-dependency-versions-in-cargo-toml/71277>.

Add minimal versions test to CI

---

src/redirect.rs
tests/redirects.rs

Fix various aspects of the `auto_referer` option:
- Fix multiple `Referer` headers being included when two or more redirects are followed in a request
- URL fragments and userinfo parts of the authority should not be included in the `Referer` header
- Don't include a `Referer` header when redirecting from an HTTPS URL to an HTTP URL, as per [RFC 7231](https://httpwg.org/specs/rfc7231.html#header.referer) recommendation
- Scrub sensitive headers when redirecting to a different authority
Fixes #392

Auto-referer header fixes

---

Cargo.toml

This updates the bundled curl version to 7.83.1, which fixes several new CVEs.

Upgrade curl-sys to 0.4.55

---

src/cookies/cookie.rs

Clarify that `CookieBuilder::domain` does not handle any prefixes specific to the parsing of the `Set-Cookie` header in the function documentation.
See #387.

Add note about cookie domain prefix in docs

---

benchmarks/Cargo.toml
benchmarks/benches/download.rs

Signed-off-by: Xuanwo <github@xuanwo.io>
---
This PR will add `reqwest` (with the `blocking` feature enabled) to benchmarks so that we can measure the perf with reqwest(hyper).

feat(benches): Add bench with reqwest blocking

---

Cargo.toml
src/agent/hasher.rs
src/agent/mod.rs
src/agent/selector.rs
src/client.rs
src/handler.rs

Remove the following dependencies:
- `rustls-ffi`: We don't actually need this directly, as curl pulls it in transitively as needed. Listing this as a direct dependency was unnecessary.
- `slab`: Performance testing yields no significant memory or performance improvements over just using a `HashMap` for our purposes, so replace the one occurrence of slab in the agent with a `HashMap` using a unique ID derived from the curl easy handle to keep track of requests.
Also add comments to `Cargo.toml` next to each runtime dependency which explains how the dependency is used and why it is there.

More dependency pruning with comments

---

src/cookies/psl/mod.rs

Make PSL system less reliant on statics and easier to reliably test. In the future we might do more internal refactoring to make the PSL cache tied to individual clients, but I'm saving that for later.

More PSL internal refactoring

---

Cargo.toml
examples/async.rs
src/agent/mod.rs
src/body/mod.rs
src/body/sync.rs
src/client.rs
src/handler.rs
src/lib.rs
src/response.rs
src/text.rs
src/util/future.rs
src/util/io.rs
src/util/mod.rs
src/util/task.rs
tests/json.rs
tests/request_body.rs

Disable default features in `futures-lite` which require several dependencies that are actually unnecessary for the very few things we use from it. Re-implement these few features instead.

Remove several features from futures-lite
